// <auto-generated />
namespace QLKS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Craete_Table_HOADON : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Craete_Table_HOADON));
        
        string IMigrationMetadata.Id
        {
            get { return "202105031424546_Craete_Table_HOADON"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
